services:
  - type: web
    name: student-performance-analysis-front
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
